apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32000
  selector:
    app: registry
  type: NodePort
status:
  loadBalancer: {}
