apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: [ "sh", "-c", "env && sleep 3600" ]
    envFrom:
    - configMapRef:
        name: app-whatever
    - secretRef:
        name: app-tls
