apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: default
  labels:
    name: backend
spec:
  containers:
  - name: cont-be
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
      targetPort
