apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: alpine:latest
    command: [ 'sh', '-c', 'while true; do echo "logging $(date)" >> /opt/logs.txt; sleep 1; done' ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: data
      mountPath: /opt

  - name: logshipper
    image: alpine:latest
    command: [ 'sh', '-c', 'tail -F /opt/logs.txt' ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: data
      mountPath: /opt
  volumes:
  - name: data
    emptyDir: {}
